from e2e_0921_common import *
with sync_playwright() as pw:
 b=pw.chromium.launch(headless=True);page=b.new_page(viewport={'width':1280,'height':720});page.set_default_timeout(5000);login(page)
 def task(name,fn):
  try:fn()
  except Exception as e:results[name+'-error']=str(e);print(name,traceback.format_exc())
  save('resume-final')
 def resume():
  go(page,f'/projects/{pid}/my-tests');results['assigned-start']=capture(page,'assigned-start');page.get_by_role('link',name='Open test',exact=True).click();page.wait_for_timeout(400);results['assigned-open']=capture(page,'assigned-open');page.reload(wait_until='networkidle');results['assigned-refresh']=capture(page,'assigned-refresh')
  data=json.loads((OUT/'e2e-0921-resume.json').read_text(encoding='utf-8'))['results']['setup'];plid=data['plan']['id'];go(page,f'/projects/{pid}/plans/{plid}');page.get_by_role('link',name=re.compile('Open run')).click();page.wait_for_timeout(400);results['plan-open']=capture(page,'plan-open');results['plan-run-api']=api('GET','/api/runs/'+page.url.split('/runs/')[1].split('?')[0]);results['runs-overview-api']=api('GET',f'/api/projects/{pid}/runs-overview');go(page,f'/projects/{pid}/runs');page.get_by_role('link',name=re.compile('Run B Firefox')).first.click();page.wait_for_timeout(400);results['list-open']=capture(page,'list-open');go(page,f'/projects/{pid}');page.get_by_role('link',name=re.compile('Run A Chrome')).first.click();page.wait_for_timeout(400);results['overview-open']=capture(page,'overview-open')
 def dynamic():
  c=api('POST',f'/api/sections/{leaf}/cases',{'title':'Dynamic high smoke','priority':'high'})['data'];r=api('POST',f'/api/projects/{pid}/runs',{'name':'Review dynamic high','suiteId':int(sid),'includeAll':False,'compositionMode':'dynamic_filter','filterDefinition':{'priority':'high','state':'active'}});rid=r['run']['id'];go(page,f'/projects/{pid}/runs/{rid}');results['dynamic-before']=capture(page,'dynamic-before');api('POST',f'/api/sections/{leaf}/cases',{'title':'Dynamic high new','priority':'high'});api('POST',f'/api/sections/{leaf}/cases',{'title':'Dynamic low excluded','priority':'low'});page.reload(wait_until='networkidle');page.wait_for_timeout(300);results['dynamic-after']=capture(page,'dynamic-after');results['dynamic-api']=api('GET',f'/api/runs/{rid}');results['selected-still-six']=api('GET',f'/api/runs/{fx["runs"][0]["run"]["id"]}')
 def attachment():
  rid=fx['runs'][1]['run']['id'];tid=fx['runs'][1]['instances'][2]['id'];go(page,f'/projects/{pid}/runs/{rid}?testId={tid}');page.get_by_role('button',name='Add result',exact=True).click();d=page.get_by_role('dialog');d.get_by_label('Status',exact=True).select_option(label='Failed');d.locator('input[type=file]').set_input_files({'name':'retry-retained.txt','mimeType':'text/plain','buffer':b'isolated review bytes'});d.get_by_role('button',name='Add Result',exact=True).click();page.wait_for_timeout(400);results['attachment-before']=api('GET',f'/api/tests/{tid}/results');page.keyboard.press('Escape');page.get_by_role('button',name='Leave',exact=True).click();page.wait_for_timeout(300);page.get_by_role('button',name='Add result',exact=True).click();results['attachment-reopened']=capture(page,'attachment-reopened');page.get_by_role('dialog').get_by_role('button',name='Retry',exact=True).first.click();page.wait_for_timeout(400);results['attachment-retry']=capture(page,'attachment-retry');results['attachment-after']=api('GET',f'/api/tests/{tid}/results')
 for n,fn in [('resume',resume),('dynamic',dynamic),('attachment',attachment)]:task(n,fn)
 b.close()
