export const TESTRAIL_V2_SUPPORTED = [
  "GET get_projects",
  "GET get_case/{case_id}",
  "GET get_cases/{project_id}",
  "GET get_suites/{project_id}",
  "GET get_sections/{project_id}",
  "GET get_milestones/{project_id}",
  "GET get_plans/{project_id}",
  "GET get_statuses",
  "GET get_configs/{project_id}",
  "GET get_case_fields/{project_id}",
  "GET get_result_fields/{project_id}",
  "GET get_templates/{project_id}",
  "GET get_users",
  "GET get_users/{project_id}",
  "GET get_reports/{project_id}",
  "GET get_roles",
  "GET get_attachments_for_case/{case_id}",
  "GET get_attachments_for_result/{result_id}",
  "GET get_run/{run_id}",
  "GET get_tests/{run_id}",
  "POST run_report/{report_id}",
  "POST add_case/{section_id}",
  "POST update_case/{case_id}",
  "POST add_run/{project_id}",
  "POST add_result_for_case/{run_id}/{case_id}",
  "POST add_results_for_cases/{run_id}"
] as const;

export const TESTRAIL_V2_DEFERRED = [
  "get_project",
  "get_suite",
  "get_section",
  "get_milestone",
  "get_plan",
  "get_results",
  "get_results_for_case",
  "get_results_for_run",
  "add_suite",
  "update_suite",
  "add_section",
  "update_section",
  "delete_section",
  "close_run",
  "update_run",
  "get_case_types",
  "get_priorities"
] as const;
